# Geometric morphometrics 

## Load packages + data

```{r load.packages, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# load required analysis packages
library(here)
library(StereoMorph)
library(geomorph)
library(tidyverse)
library(wesanderson)
library(ggplot2)

# read data and define number of sLMs ----
shapes <- readShapes("shapes")
shapesGM <- readland.shapes(shapes, nCurvePts = c(50,50))

# read qualitative data
qdata <- read.csv("qdata.morph.csv", 
                  header = TRUE, 
                  row.names = 1)
```

## Generalised Procrustes Analysis

```{r outlines, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# gpa ----
Y.gpa <- gpagen(shapesGM, print.progress = FALSE)

# geomorph data frame ----
gdf <- geomorph.data.frame(shape = Y.gpa$coords, 
                           size = Y.gpa$Csize,
                           merged = qdata$merged)


# add centroid size to qdata
qdata$csz <- Y.gpa$Csize

# attributes for boxplot
csz <- qdata$csz # centroid size
site <-  qdata$site # site

# boxplot of Jowell knife centroid size by site ----
csz.site <- ggplot(qdata, aes(x = merged, y = csz, color = merged)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 0.3) +
  scale_colour_manual(values = wes_palette("Moonrise2")) +
  theme(legend.position = "none") +
  labs(x = 'Site', y = 'Centroid Size')

# render boxplot
csz.site
```

## Principal Components Analysis

```{r pca.plot, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# principal components analysis ----
pca<-gm.prcomp(Y.gpa$coords)
summary(pca)

# set plot parameters
pch.gps <- c(1:4)[as.factor(qdata$merged)]
col.gps <- wes_palette("Moonrise2")[as.factor(qdata$merged)]
col.hull <- c("#CCC591", "#29211F", "#798E87", "#C27D38")

# plot pca by site
pc.plot <- plot(pca, 
                asp = 1,
                pch = pch.gps,
                col = col.gps)
shapeHulls(pc.plot, 
           groups = qdata$merged,
           group.cols = col.hull)
```

## ANOVA

```{r anova, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# ANOVA ----
# size
fit.sz <- procD.lm(size ~ merged,
                   data = gdf,
                   print.progress = FALSE,
                   iter = 9999)

anova(fit.sz)

# pairwise comparison of LS means = which differ?
pw.sz <- pairwise(fit.sz,
                  groups = qdata$merged)
summary(pw.sz, 
        confidence = 0.95, 
        test.type = "dist")

# shape
fit.sh <- procD.lm(shape ~ merged,
                   data = gdf,
                   print.progress = FALSE,
                   iter = 9999)

anova(fit.sh)

# pairwise comparison of LS means = which differ?
pw.sh <- pairwise(fit.sh,
                  groups = qdata$merged)
summary(pw.sh, 
        confidence = 0.95, 
        test.type = "dist")
```

## Trajectory Analysis

```{r ms1, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# trajectory analysis::shape----
TA <- trajectory.analysis(fit.sh,
                          groups = qdata$site, 
                          traj.pts = qdata$size,
                          print.progress = FALSE)

# magnitude difference
summary(TA, 
        attribute = "MD",
        show.trajectories = TRUE)

# plot
TP <- plot(TA, 
           pch = as.numeric(qdata$site), 
           bg = as.numeric(qdata$size),
           cex = 0.9,
           col = "gray")
add.trajectories(TP, 
                 traj.pch = c(1,2),
                 traj.cex = 1)
```

## Morphological Disparity

```{r mdisp, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# morphological disparity ----
# do any of the groups display greater shape variation among 
# individuals relative to the other group?
morphol.disparity(shape ~ merged,
                  groups = qdata$merged, 
                  data = gdf, 
                  print.progress = FALSE, 
                  iter = 9999)
```

## Mean Shapes

```{r mshape, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# mean shapes ----
# subset landmark coordinates to produce mean shapes
new.coords<-coords.subset(A = Y.gpa$coords,
                          group = qdata$merged)
names(new.coords)

# group shape means
mean <- lapply(new.coords, mshape)

# comparison plots
plotRefToTarget(mean$AN13_L,
                mean$HS261_L, 
                method = c("point"),
                mag = 2)
```
