# Assign size class

```{r load.linear, echo=TRUE}
# load analysis libraries
library(here)
library(tidyverse)
library(EnvStats)
library(ggpubr)
library(ggfortify)
library(cluster)
library(ggExtra)
library(RRPP)
library(wesanderson)

# load data
size.class <- read.csv("qdata.csv",
                          header = TRUE,
                          as.is = TRUE)
```

## Millsap Cache

```{r sizenorth, echo=TRUE, warning=FALSE}
# subset millsap dataset
millsap <- subset(size.class,
                  site == "Millsap Cache")

# calculate mean length
meanl <- mean(millsap$maxl)

# assign L/S varieties
ls.check1 <- millsap$maxl >= meanl
ls.check2 <- millsap$maxl >= 0 & millsap$maxl < meanl

millsap$size <- ""
millsap$size <- ifelse(ls.check1, "L", millsap$size)
millsap$size <- ifelse(ls.check2, "S", millsap$size)
```

### Jowell Farm

```{r sizesabine, echo=TRUE, warning=FALSE}
# subset jowell dataset
jowell <- subset(size.class,
                 site == "Jowell Farm")

# calculate mean length
meanl <- mean(jowell$maxl)

# assign L/S varieties
ls.check1 <- jowell$maxl >= meanl
ls.check2 <- jowell$maxl >= 0 & jowell$maxl < meanl

jowell$size <- ""
jowell$size <- ifelse(ls.check1, "L", jowell$size)
jowell$size <- ifelse(ls.check2, "S", jowell$size)
```

### Aggregate and export

```{r}
# aggregate data
mx <- bind_rows(millsap, jowell)

# join site and size class
qdata2 <- mx %>% 
  unite("merged", site, size, remove = FALSE)

# output csv for use in gm analysis
write.csv(qdata2, "qdata.merged.csv")
```

