# Linear2

```{r load packages 3, echo=TRUE}
# install required analysis packages
#devtools::install_github("tidyverse/tidyverse")
#devtools::install_github("mlcollyer/RRPP")
#devtools::install_github("kassambara/ggpubr")
#devtools::install_github("sinhrks/ggfortify")
#devtools::install_github("karthik/wesanderson")
#devtools::install_github("daattali/ggExtra")
# load libraries
library(here)
library(tidyverse)
library(RRPP)
library(ggpubr)
library(ggfortify)
library(cluster)
library(wesanderson)
library(ggExtra)
```

## Load data + define L/S

```{r setwd ld define variables 3, echo=TRUE}
# define subsets, assign L/S----
# load data
size.class <- read.csv("sizeclass.csv",
                       header = TRUE,
                       as.is=TRUE)
```

## Boxplots for _variable_ by _site_

```{r boxsite, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE, fig.cap = "Boxplots for maximum length, width, and thickness for Jowell knives from 41AN13 and 41HS261."}
# boxplot of maximum length ~ site
sitemaxl <- ggplot(size.class, aes(x = merged, y = length, color = merged)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 0.3) +
  scale_colour_manual(values = wes_palette("Moonrise2")) +
  theme(legend.position = "none") +
  labs(x = 'Site', y = 'MaxL')

# boxplot of maximum width ~ site
sitemaxw <- ggplot(size.class, aes(x = merged, y = width, color = merged)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 0.3) +
  scale_colour_manual(values = wes_palette("Moonrise2")) +
  theme(legend.position = "none") +
  labs(x = 'Site', y = 'MaxW')

# boxplot of maximum thickness ~ site
sitemaxth <- ggplot(size.class, aes(x = merged, y = thickness, color = merged)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 0.3) +
  scale_colour_manual(values = wes_palette("Moonrise2")) +
  theme(legend.position = "none") +
  labs(x = 'Site', y = 'MaxTh')

# render figure
sitefigure<-ggarrange(sitemaxl,sitemaxw,sitemaxth,
                  labels = c("a","b","c"),
                  ncol = 2, nrow = 2)
              
# plot figure
sitefigure
```

## Principal Components Analysis for _site_

```{r pcasite, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE, fig.cap = "Principal Components Analysis by site."}
#attributes for plot
merged <- size.class$merged
df <- size.class[c(4:6)]
pch.gps.gp <- c(15:18)[as.factor(merged)]

#pca
pca <- autoplot(prcomp(df),
         data = size.class,
         asp = 1,
         shape = pch.gps.gp,
         colour = 'merged',
         loadings = TRUE, 
         loadings.colour = 'blue',
         loadings.label = TRUE,
         loadings.label.size = 3, 
         frame = TRUE) +
    scale_fill_manual(values = wes_palette("Moonrise2")) +
    scale_colour_manual(values = wes_palette("Moonrise2"))

ggMarginal(pca, groupColour = TRUE, groupFill = TRUE)
```

## Analyses of Variance (ANOVA) for _variable_ ~ _site_

### _Maximum length_ of Jowell knives

```{r anovasitemaxl, out.width = "100%", dpi = 300, echo=TRUE}
# anova = maximum length ~ site
siteml <- lm.rrpp(length ~ merged, 
                  SS.type = "I", 
                  data = size.class, 
                  iter = 9999, 
                  print.progress = FALSE)

# difference in max length by size class?
anova(siteml)

# pairwise comparison of LS means = which differ?
sh.pwml <- pairwise(siteml,
                    groups = size.class$merged)
summary(sh.pwml, 
        confidence = 0.95, 
        test.type = "dist")
```

### _Maximum width_ of Jowell knives

```{r anovasitemaxw, out.width = "100%", dpi = 300, echo=TRUE}
# anova = maximum width ~ site
sitemw <- lm.rrpp(width ~ merged, 
                  SS.type = "I", 
                  data = size.class, 
                  iter = 9999, 
                  print.progress = FALSE)

anova(sitemw)
```

### _Maximum thickness_ of Jowell knives

```{r anovasitemaxth, out.width = "100%", dpi = 300, echo=TRUE}
# anova = maximum thickness ~ site
sitemth <- lm.rrpp(thickness ~ merged, 
                   SS.type = "I", 
                   data = size.class, 
                   iter = 9999, 
                   print.progress = FALSE)

# difference in max thickness by size class?
anova(sitemth)

# pairwise comparison of LS means = which differ?
sh.pwmth <- pairwise(sitemth,
                     groups = size.class$merged)
summary(sh.pwmth, 
        confidence = 0.95, 
        test.type = "dist")
```
